ARG PYTHON_VERSION=3.14

FROM python:${PYTHON_VERSION}-slim

COPY /src /src
WORKDIR /src

COPY ./uv.lock /src/uv.lock
COPY pyproject.toml /pyproject.toml
RUN pip install uv
RUN uv sync

COPY provision/entrypoint.sh /src/entrypoint.sh
RUN chmod +x /src/entrypoint.sh

ENTRYPOINT [ "/src/entrypoint.sh" ]